CREATE TABLE `achievements` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`createdAt` integer DEFAULT (strftime('%s','now')) NOT NULL,
	`updatedAt` integer DEFAULT (strftime('%s','now')) NOT NULL,
	`userId` integer NOT NULL,
	`key` text NOT NULL,
	`title` text NOT NULL,
	`description` text DEFAULT '',
	`icon` text DEFAULT '🏆',
	`points` integer DEFAULT 10,
	`achievedAt` integer DEFAULT '"2025-11-01T02:57:57.976Z"',
	`type` text DEFAULT 'misc',
	`linkedHabitId` integer,
	FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`linkedHabitId`) REFERENCES `habits`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `achievements_key_unique` ON `achievements` (`key`);--> statement-breakpoint
CREATE TABLE `habit_logs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`createdAt` integer DEFAULT (strftime('%s','now')) NOT NULL,
	`updatedAt` integer DEFAULT (strftime('%s','now')) NOT NULL,
	`habitId` integer NOT NULL,
	`userId` integer NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`logDate` integer NOT NULL,
	`note` text DEFAULT '',
	`value` integer DEFAULT 1,
	`mood` text DEFAULT '',
	`autoGenerated` integer DEFAULT false,
	FOREIGN KEY (`habitId`) REFERENCES `habits`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `habits` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`createdAt` integer DEFAULT (strftime('%s','now')) NOT NULL,
	`updatedAt` integer DEFAULT (strftime('%s','now')) NOT NULL,
	`userId` integer NOT NULL,
	`title` text NOT NULL,
	`description` text DEFAULT '',
	`category` text DEFAULT 'general',
	`frequency` text DEFAULT 'daily',
	`customFrequency` text DEFAULT '',
	`startTime` text DEFAULT '',
	`endTime` text DEFAULT '',
	`startDate` integer DEFAULT '"2025-11-01T02:57:57.976Z"',
	`endDate` integer DEFAULT '"1970-01-01T00:00:00.000Z"',
	`inCalendar` integer DEFAULT false,
	`goalPerDay` integer DEFAULT 1,
	`totalCompletions` integer DEFAULT 0,
	`currentStreak` integer DEFAULT 0,
	`longestStreak` integer DEFAULT 0,
	`lastCompletedAt` integer DEFAULT '"1970-01-01T00:00:00.000Z"',
	`colorTag` text DEFAULT '#A78BFA',
	`icon` text DEFAULT '✨',
	`visibility` text DEFAULT 'private',
	`difficulty` text DEFAULT 'medium',
	`rewardTag` text DEFAULT '',
	`locationTag` text DEFAULT '',
	`isArchived` integer DEFAULT false,
	`isPaused` integer DEFAULT false,
	FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `moods` (
	`userId` integer NOT NULL,
	`moodLevel` integer NOT NULL,
	`moodLabel` text DEFAULT 'Neutral',
	`note` text DEFAULT '',
	`emoji` text DEFAULT '',
	`energyLevel` integer DEFAULT 5,
	`stressLevel` integer DEFAULT 5,
	`loggedAt` integer DEFAULT '"2025-11-01T02:57:57.987Z"',
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`createdAt` integer DEFAULT (strftime('%s','now')) NOT NULL,
	`updatedAt` integer DEFAULT (strftime('%s','now')) NOT NULL,
	FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `notifications` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`createdAt` integer DEFAULT (strftime('%s','now')) NOT NULL,
	`updatedAt` integer DEFAULT (strftime('%s','now')) NOT NULL,
	`userId` integer NOT NULL,
	`habitId` integer,
	`title` text NOT NULL,
	`message` text DEFAULT '',
	`type` text DEFAULT 'reminder',
	`scheduledFor` integer NOT NULL,
	`sentAt` integer DEFAULT '"1970-01-01T00:00:00.000Z"',
	`delivered` integer DEFAULT false,
	`read` integer DEFAULT false,
	`openedAt` integer DEFAULT '"1970-01-01T00:00:00.000Z"',
	`channel` text DEFAULT 'local',
	FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`habitId`) REFERENCES `habits`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `users` (
	`name` text NOT NULL,
	`email` text NOT NULL,
	`password` text NOT NULL,
	`avatarUrl` text DEFAULT '',
	`bio` text DEFAULT '',
	`timezone` text DEFAULT 'UTC',
	`joinedAt` integer DEFAULT (strftime('%s','now')),
	`totalHabitsCreated` integer DEFAULT 0,
	`totalCompletions` integer DEFAULT 0,
	`streakLongest` integer DEFAULT 0,
	`streakCurrent` integer DEFAULT 0,
	`theme` text DEFAULT 'light',
	`notificationsEnabled` integer DEFAULT true,
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`createdAt` integer DEFAULT (strftime('%s','now')) NOT NULL,
	`updatedAt` integer DEFAULT (strftime('%s','now')) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);