import { int, sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { habitsTable } from "./habits.table";
import { usersTable } from "./user.table";
import baseFields from "./shared.fields";

export const habitLogsTable = sqliteTable("habit_logs", {
  ...baseFields,
  habitId: int().notNull().references(() => habitsTable.id),
  userId: int().notNull().references(() => usersTable.id),

  status: text({ enum: ["completed", "pending", "missed", "dropped", "deleted"] })
    .notNull()
    .default("pending"),

  logDate: integer({ mode: "timestamp" }).notNull(), // actual day being logged (midnight timestamp)
  note: text().default(""),
  value: int().default(1), // could represent intensity or count (e.g., 3 pomodoros)
  mood: text().default(""), // optional mood after completion
  autoGenerated: int({ mode: "boolean" }).default(false), // for system-generated "missed" entries
});
